services:

  mongo:
    image: mongo
    container_name: mongo
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ADMINUSERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMINPASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    volumes:
      - docker_db:/docker_db
    ports:
      - "${MONGODB_PORT}:27017"
    networks:
      - docker_network
    deploy:
      resources:
        limits:
          cpus: '0.5'       # half CPU core
          memory: 512M      # 512 MB RAM
        reservations:
          cpus: '0.25'      # minimum CPU reserved
          memory: 256M      # minimum memory reserved
  
  nginx:
    build: 
      context: .
      dockerfile: ./Docker/Dockerfile.nginx
    container_name: nginx
    volumes:
      - docker_db:/docker_db
    ports:
      - "80:80"
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - docker_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M 
        reservations:
          cpus: '0.25'
          memory: 256M 

  server1:
    build: 
      context: .
      dockerfile: ./Docker/Dockerfile
    container_name: server1
    env_file:
      - .env
    volumes:
      - docker_db:/docker_db
    ports:
      - "1111:${PORT}"
    networks:
      - docker_network
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M 

  server2:
      build: 
        context: .
        dockerfile: ./Docker/Dockerfile
      container_name: server2
      env_file:
        - .env
      volumes:
        - docker_db:/docker_db
      ports:
        - "2222:${PORT}"
      networks:
        - docker_network
      depends_on:
        - mongo
      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: 512M
          reservations:
            cpus: '0.25'
            memory: 256M 

  server3:
      build: 
        context: .
        dockerfile: ./Docker/Dockerfile
      container_name: server3
      env_file:
        - .env
      volumes:
        - docker_db:/docker_db
      ports:
        - "3333:${PORT}"
      networks:
        - docker_network
      depends_on:
        - mongo
      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: 512M 
          reservations:
            cpus: '0.25'
            memory: 256M 

networks:
  docker_network:

volumes:
  docker_db: