FROM nginx:alpine

# Install envsubst
RUN apk add --no-cache gettext

# Copy the template
COPY ../conf/nginx/default.conf /etc/nginx/default.conf

# Use CMD to dynamically inject PORT and start Nginx
CMD envsubst '${PORT}' < /etc/nginx/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
