

export enum SUBSCRIPTION_TYPE {
    SUBSCRIBED = "SUBSCRIBED",
    SUBSCRIPTION_PLAN = "SUBSCRIPTION_PLAN"
}

export enum SUBSCRIPTION_STATUS {
    ACTIVE = "ACTIVE",
    DEACTIVE = "DEACTIVE"
}

export enum SUBSCRIPTION_DURATION_TIME {
    MONTHLY = "MONTHLY",
    YEARLY = "YEARLY"
}

